In [1]:
a = round(3.19 +3.19 + 3.19+3.19 +3.19 + 3.19 +3.19 +3.19 , 2)
b = 3.19 *8

In [2]:
print(a)
print(b)

25.52
25.52


In [3]:
a==b

True

In [4]:
x=3.19 +3.19 + 3.19+3.19
y=3.19 *4
print(x)
print(y)

12.76
12.76


In [5]:
x==y

True

In [6]:
f  = open('test.txt', 'w+')
print("Simplilearn", file = f)
f.close()

#### Agenda:

- Fundamentals of Numpy
    * Advantages
    * Installation
- Array 
    `* Creating Numpy array

Numpy is an opensource  librarry that is primarily used for mathematical and scientific calculations. it allows the usage of Arras which are not available as data structure in python core modules

In [7]:
#Install Numpy

!pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [8]:
# Importing numpy

In [9]:
import numpy as np

In [10]:
a =  np.array([10,20,30,40.5])

In [11]:
print(a)

[10.  20.  30.  40.5]


In [12]:
b = [10,20,30,40.5]
print(b)

[10, 20, 30, 40.5]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(type(b))

<class 'list'>


In [15]:
print(id(a[0]))
print(id(a[1]))
print(id(a[2]))
print(id(a[3]))

140610318527792
140610318526576
140610318527600
140610318527600


In [16]:
print(id(b[0]))
print(id(b[1]))
print(id(b[2]))
print(id(b[3]))

140610995864080
140610995864400
140610995864720
140610318526544


In [18]:
import numpy as np
import time # using for capturingting the epoch(unix) time -  time is seconds/ms elasped sinch epoch( Jan 1st 1970 00:00:00)

In [19]:
time.time()

1708527033.5490918

In [20]:
time.time()

1708527116.5961807

In [21]:
1708527116.5961807 - 1708527033.5490918

83.04708886146545

In [22]:
X = np.random.rand(100000000)

In [23]:
start = time.time()
avg = sum(X)/100000000
stop = time.time()
print(stop-start)

5.56976580619812


In [24]:
start = time.time()
avgnp = np.mean(X)
stop = time.time()
print(stop-start)

0.0484929084777832


In [25]:
# Create Array - Syntax is 
# numpy.array(<lists>)

In [26]:
# Create 0darray
X = np.array(34)
print(X)
print(X.ndim)

34
0


In [28]:
# Create 1darray
X = np.array([1,2,3,4,5])
print(X)
print(X.ndim)

[1 2 3 4 5]
1


In [30]:
# Create 2darray
X = np.array([[1,2,3,4,5], [11,12,13,14,15]])
print(X)
print(X.ndim)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
2


In [31]:
# Create 2darray
X = np.array([[[1,2,3,4,5], [11,12,13,14,15]], [[1,2,3,4,5], [11,12,13,14,15]]])
print(X)
print(X.ndim)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [11 12 13 14 15]]]
3


In [32]:
X =  np.array([[1,2], [2,3], [3,4]])
print(X)

[[1 2]
 [2 3]
 [3 4]]


In [45]:
Y = np.array([[1,2,3,4]])

In [44]:
Y.ndim

2

In [46]:
print(Y)

[[1 2 3 4]]


In [47]:
# Attributes and Functions

In [48]:
array1 = np.array([[1,2,3], [11,12,13]])

In [50]:
array1 = np.array([[1,2,3], [11,12,13]])
print(array1)
print("No of dimensions : ", array1.ndim)
print("Shape of array : ", array1.shape)
print("Size of array : ", array1.size)
print("datatype of array elements: ", array1.dtype)
print("length  of one array element in memory in bytes: ", array1.itemsize)

[[ 1  2  3]
 [11 12 13]]
No of dimensions :  2
Shape of array :  (2, 3)
Size of array :  6
datatype of array elements:  int64
length  of one array element in memory in bytes:  8


In [51]:
array2 = np.array([[[1,2,3], [11,12,13]]])
print(array2)
print("No of dimensions : ", array2.ndim)
print("Shape of array : ", array2.shape)
print("Size of array : ", array2.size)
print("datatype of array elements: ", array2.dtype)
print("length  of one array element in memory in bytes: ", array2.itemsize)

[[[ 1  2  3]
  [11 12 13]]]
No of dimensions :  3
Shape of array :  (1, 2, 3)
Size of array :  6
datatype of array elements:  int64
length  of one array element in memory in bytes:  8


In [52]:
array3 = np.array([[[1,2,3,4,5], [11,12,13,14,15]], [[1,2,3,4,5], [11,12,13,14,15]]])

In [53]:
print(array3.shape)

(2, 2, 5)


In [54]:
print(array3)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [11 12 13 14 15]]]


In [58]:
array4 = np.arange(1,28).reshape(3,3,3)

In [59]:
print(array4)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [57]:
array4.shape

(3, 3, 3)

In [60]:
# Basic Functions

In [61]:
#reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [62]:
arr.shape

(12,)

In [65]:
newarr = arr.reshape(2,3,2)

In [66]:
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [68]:
newarr = newarr.reshape(4,3)

In [71]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
newarr.reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
newarr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [73]:
np.ravel(newarr, order = 'F') # Fortran Based Access

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [74]:
np.ravel(newarr, order = 'C') # C Based Access

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
newarr.shape

(4, 3)

In [76]:
newarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
# Transpose

In [78]:
newarr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [79]:
newarr.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [80]:
# Arithmetic, statistical , string ops in numpy

In [81]:
# Arithmetic OPerations -  are done one element wise basis

In [82]:
a = np.array([10,20,30])
b = np.array([2,4,5])

In [83]:
a+b

array([12, 24, 35])

In [84]:
np.add(a,b)

array([12, 24, 35])

In [85]:
a-b

array([ 8, 16, 25])

In [86]:
np.subtract(a,b)

array([ 8, 16, 25])

In [87]:
a*b

array([ 20,  80, 150])

In [88]:
np.multiply(a,b)

array([ 20,  80, 150])

In [89]:
a/b

array([5., 5., 6.])

In [90]:
np.divide(a,b)

array([5., 5., 6.])

In [91]:
a**b

array([     100,   160000, 24300000])

In [92]:
np.power(a,b)

array([     100,   160000, 24300000])

In [93]:
print(-5/2)

-2.5


In [94]:
print(-5//2)

-3


In [95]:
#  // =  Floor Division -  nearest integer moving towrds negative infinity

In [96]:
# Statistical Functions

In [110]:
ar =  np.array([[34,12,11], [23,56,12],[23,34,2]])

In [111]:
# median

In [112]:
np.median(ar)

23.0

In [113]:
np.percentile(ar, 50)

23.0

In [122]:
np.mean(ar)

23.0

In [124]:
np.std(ar)

15.484759532449246

In [125]:
np.var(ar)

239.77777777777777

In [126]:
15.484759532449246**2

239.7777777777778

In [127]:
# String Functions