In [3]:
print("Hello World")

Hello World


# Array

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
l=[]
for i in range(1,4):
    x=int(input("Enter : "))
    l.append(x)
print(l)
print(type(l))

Enter :  4
Enter :  3
Enter :  2


[4, 3, 2]
<class 'list'>


## 2-D Array

In [15]:
import numpy as np
a2=np.array([[1,2,3,4],[1,2,3,4]])
print(a2)
print(a2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


## 3-D Array

In [12]:
import numpy as np
a2=np.array([[[1,2,3]]])
print(a2)
print(a2.ndim)

[[[1 2 3]]]
3


## Multi-Dimensional Array

In [18]:
import numpy as np
am = np.array([1, 2, 3, 4], ndmin=5)
print(am)
print('number of dimensions :', am.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Spepcial Types of Array

## Array filled with 0

In [20]:
# 1-d
import numpy as np
a=np.zeros(4)
print(a)
# 3-d
b=np.zeros((3,4))
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array filled with 1

In [21]:
# 1-d
import numpy as np
a=np.ones(4)
print(a)
# 3-d
b=np.ones((3,4))
print(b)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating an empty array

In [23]:
# previoous memory ka data show krra so all okayy
ae=np.empty(4)
print(ae)

[1. 1. 1. 1.]


## An Array with a Range of Elements  

In [24]:
ar=np.arange(4)
print(ar)

[0 1 2 3]


## Array wtih Diagonal filled with 1's

In [31]:
ad=np.eye(3)
print(ad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
ad=np.eye(4,6)
print(ad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


## Evenly spaced array

In [36]:
al=np.linspace(0,20,num=5)
print(al)

[ 0.  5. 10. 15. 20.]


# Creating Random Values Array 

## Generate Random Number

In [42]:
from numpy import random
x = random.randint(10)
print(x)

7


## rand()

In [43]:
import numpy as np
a=np.random.rand(3) # 1-d
print(a)
b=np.random.rand(2,5) # multi-d
print(b)

[0.79871332 0.11606003 0.32528704]
[[0.3440296  0.69748484 0.41872381 0.39754789 0.10050466]
 [0.98087411 0.38794905 0.81396146 0.52603967 0.96818621]]


## randn()

In [45]:
a=np.random.randn(3)
print(a)

[-0.66094218  1.59182057  1.33861239]


## ranf()

In [46]:
a=np.random.ranf(4)
print(a)

[0.23001553 0.84282357 0.73482437 0.3423785 ]


## choice()

In [48]:
# return a number from this array only
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)


5


In [52]:
# shuffle the entire array and return random array with this value only
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 3 7 7 5]
 [5 3 5 3 9]
 [9 9 7 5 7]]


# Data Type In Numpy

## Checking Data Type of Array

In [53]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


## Creating Array with a Defined Data Type

In [58]:
# arr = np.array([1, 2, 3, 4], dtype='i1')
# arr = np.array([1, 2, 3, 4], dtype='i2')
# arr = np.array([1, 2, 3, 4], dtype='i4')
# arr = np.array([1, 2, 3, 4], dtype='S')
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [64]:
# creating with the help of the function
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)
# function type-1
new=np.float32(arr)
print(new)
print(new.dtype)
# function type-2
new2=arr.astype('S')
print(new2)
print(new2.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float32
[b'1' b'2' b'3' b'4']
|S11


# Shape & Reshape in Numpy Array

## Shape

In [66]:
import numpy as np
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a)
print(a.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


## Reshape

In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)
# chnge to 2-d
x=a.reshape(3,2)
print(x)
print(x.ndim)
# chnge to 3-d
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=b.reshape(2,3,2)
print(y)
print(y.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [7]:
# changing 3-d to 1-d
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# 3-d
y=b.reshape(2,3,2)
print(y)
print(y.ndim)
# 1-d
one=y.reshape(-1)
print(one)
print(one.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Arthimetic Operations

## Add

In [4]:
import numpy as np
v=np.array([1,2,3,4])
va=v+3
print(va)

[4 5 6 7]


In [14]:
v1=np.array([1,2,3,4])
v2=np.array([1,2,3,4])
va=np.add(v1,v2)
print(va)

[2 4 6 8]


## Subtraction

In [6]:
import numpy as np
v=np.array([1,2,3,4])
va=v-3
print(va)

[-2 -1  0  1]


In [16]:
v1=np.array([1,2,3,4])
v2=np.array([1,2,3,4])
va=np.subtract(v1,v2)
print(va)

[0 0 0 0]


## Multiply

In [8]:
import numpy as np
v=np.array([1,2,3,4])
va=v*3
print(va)

[ 3  6  9 12]


In [17]:
v1=np.array([1,2,3,4])
v2=np.array([1,2,3,4])
va=np.multiply(v1,v2)
print(va)

[ 1  4  9 16]


## Divide

In [10]:
import numpy as np
v=np.array([1,2,3,4])
va=v/3
print(va)

[0.33333333 0.66666667 1.         1.33333333]


In [18]:
v1=np.array([1,2,3,4])
v2=np.array([1,2,3,4])
va=np.divide(v1,v2)
print(va)

[1. 1. 1. 1.]


## Modulus

In [11]:
import numpy as np
v=np.array([1,2,3,4])
va=v%3
print(va)

[1 2 0 1]


In [24]:
v1=np.array([1,2,3,4])
v2=np.array([1,2,3,4])
va=np.mod(v1,v2)
print(va)

[0 0 0 0]


## Reciprocal

In [26]:
import numpy as np
v=np.array([1,2,3,4])
va=np.reciprocal(v)
print(va)

[1 0 0 0]


## Operations on 2-D

In [22]:
# Addition
import numpy as np
v1=np.array([[1,2,3,4],[1,2,3,4]])
v2=np.array([[1,2,3,4],[1,2,3,4]])
va=np.add(v1,v2)
# print(v1)
# print(v2)
print(va)

[[2 4 6 8]
 [2 4 6 8]]


In [23]:
# Subtraction
import numpy as np
v1=np.array([[1,2,3,4],[1,2,3,4]])
v2=np.array([[1,2,3,4],[1,2,3,4]])
va=np.subtract(v1,v2)
print(va)

[[0 0 0 0]
 [0 0 0 0]]


In [27]:
# Multiplication
import numpy as np
v1=np.array([[1,2,3,4],[1,2,3,4]])
v2=np.array([[1,2,3,4],[1,2,3,4]])
va=np.multiply(v1,v2)
print(va)

[[ 1  4  9 16]
 [ 1  4  9 16]]


## Arithmetic Function

In [35]:
import numpy as np
v=np.array([2,4,1,6,9,5])
print(np.min(v),np.argmin(v))
print(np.max(v),np.argmax(v))
print(np.sqrt(v))

1 2
9 4
[1.41421356 2.         1.         2.44948974 3.         2.23606798]


In [37]:
# sin-cos func
var=np.array([1,2,3])
print(np.sin(var))
print(np.cos(var))
ar=np.array([1,2,3,4,5])
print(np.cumsum(ar))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1  3  6 10 15]


In [34]:
# 2-d array
v=np.array([[2,4,1],[6,9,5]])
print(np.min(v,axis=0)) #col
print(np.min(v,axis=1)) #row

[2 4 1]
[1 5]


# Broadcasting

In [38]:
import numpy as np
v1=np.array([1,2,3]) # (1x3)
v2=np.array([[1],[2],[3]]) # (3x1)
print(v1+v2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a[1])
print(a[-1])

2
4


In [6]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a[0, 1])
print(a[-1, -3])

2
8


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
print(arr[-2,-1,0])

6
4


# Slicing

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print(arr[1:6:2])

[2 3 4 5]
[5 6]
[2 4 6]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,113,14,15]])
print(arr[1, 1:4])
print(arr[2, 2:4])

[7 8 9]
[113  14]


# Iteration

In [16]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
for x in arr:
  print(x)
print()
for i in arr:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]]

[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print()
for x in arr:
    for y in x:
        for z in y:
            print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating through function => nditer()

In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [42]:
arr = np.array([1, 2, 3,4,5])
# for i in np.nditer(arr):
    # print(i)
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


In [38]:
arr = np.array([1, 2, 3])
for idx,x in np.ndenumerate(arr):
  print(idx, x)
print()
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i,n in np.ndenumerate(a):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# Copy & View

In [43]:
# Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [45]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[2] = 42
print(arr)
print(x)

[ 1  2 42  4  5]
[ 1  2 42  4  5]


# Join & Spilt 

In [4]:
import numpy as np
arr1=np.array([1, 2, 3])
arr2=np.array([4, 5])
arr=np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5]


In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# axis=0 -> row || axis=1 -> caol
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Join With Stack Function

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
# arr = np.hstack((arr1, arr2))
# arr = np.vstack((arr1, arr2))
# arr = np.dstack((arr1, arr2))
print(arr)


[[1 4]
 [2 5]
 [3 6]]


## Split 

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Seraching 

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [5]:
# Search Sorted
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 10)
print(x)

4


# Sort

In [9]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
a = np.array(['banana', 'cherry', 'apple'])
print(np.sort(a))
b = np.array(['z', 'g', 'a','i', 'x', 'c',])
print(np.sort(b))

[0 1 2 3]
['apple' 'banana' 'cherry']
['a' 'c' 'g' 'i' 'x' 'z']


In [11]:
arr = np.array([[3, 2, 4], [5, 0, 1],[9,1,7]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]
 [1 7 9]]


# Filter

In [13]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)
print(type(newarr))

[41 43]
<class 'numpy.ndarray'>


# Arithmetic Function

In [14]:
# Shuffle
import numpy as np
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[3 5 1 2 4]


In [22]:
# Unique
import numpy as np
a=np.array([1,2,2,2,3,3,3,4,5,5])
b=np.unique(a)
# b=np.unique(a,return_index=True) # return index also
# b=np.unique(a,return_counts=True) # return count also
print(b)

(array([1, 2, 3, 4, 5]), array([1, 3, 3, 1, 2], dtype=int64))


In [26]:
# resize
a=np.array([1,2,3,4,5,6])
x=np.resize(a,(2,3))
# y=np.resize(a,(3,2))
print(x)
# print(y)

[[1 2 3]
 [4 5 6]]


# Insert

In [33]:
import numpy as np
a=np.array([1,2,3,5,6])
a=np.insert(a,0,4)
print(a)
b=np.array([1,2,5,6])
v=np.insert(b,(2,4),3)
print(v)

[4 1 2 3 5 6]
[1 2 3 5 6 3]


In [45]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
# b=np.insert(a,2,4,axis=0)
b=np.insert(a,2,4,axis=1)
# b=np.insert(a,2,[100,2000,300],axis=0)
print(b)

[[1 2 4 3]
 [4 5 4 6]]


# Delete

In [49]:
import numpy as np
a=np.array([1,2,3,4,9,5,6])
a=np.delete(a,4)
print(a)

[1 2 3 4 5 6]


# Matrix

## Creating a Matrix

In [51]:
import numpy as np
a=np.matrix([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


## Addition in Matrix

In [52]:
# same as 2-D array
a=np.matrix([[1,2,3],[4,5,6]])
b=np.matrix([[1,2,3],[4,5,6]])
print(a+b)

[[ 2  4  6]
 [ 8 10 12]]


## Multiplication in Matrix

In [56]:
a=np.matrix([[1,2],[4,5]])
b=np.matrix([[1,2],[4,5]])
# print(a*b)
print(a.dot(b))

[[ 9 12]
 [24 33]]


## Transpose

In [58]:
import numpy as np
a=np.matrix([[1,2,3],[4,5,6]])
print(a)
print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [62]:
a=np.matrix([[1,2,3],[4,5,6]])
print(a)
print(np.swapaxes(a,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Inverse

In [65]:
a=np.matrix([[1,2],[3,4]])
print(a)
print(np.linalg.inv(a))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [67]:
a=np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(a,2))
print(np.linalg.matrix_power(a,0))
print(np.linalg.matrix_power(a,-2))

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


## Determinant

In [68]:
a=np.matrix([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


# Statistical Function in Numpy

## Calculating Median, Mean, Standard Deviation, and Variance in the Array

In [5]:
import numpy as np
# Median
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
np.median(array)
print(np.median(array))
# Mean
np.mean(array)
print(np.mean(array))
# Standard Deviation
np.std(array)
print(np.std(array))
# Variance
np.var(array)
print(np.var(array))

4.0
6.333333333333333
6.944222218666553
48.22222222222222


## Calculating Percentiles

In [12]:
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
np.percentile(array,50)

4.0